### ISSUE TITLE
Extra Compat won['t let me join world " Cannot invoke "net.cyber_rat.extra_compat.core.CompatCore.addCreative(net.minecraftforge.event.BuildCreativeModeTabContentsEvent)" because "compatCore" is null"

### ISSUE THREAD

**Issue by BugmanBugman** [CyberRat7/Extra_Compat#10]
https://gist.github.com/BugmanBugman/7037a28365c5098cf5b82ed43e1a24e5
![2024-05-15_13 48 06](https://github.com/CyberRat7/Extra_Compat/assets/40730042/292f4cad-88b1-44ae-abc1-8ab93d686b44)
When you try to join a world with Extra Compat, this screen shows up

**Comment by BugmanBugman** [comment]
https://gist.github.com/BugmanBugman/3a090cadf03b4cb7475ca1f66d3f6ac2
getting this now

**Comment by Veynam** [comment]
same here

**Comment by CyberRat7** [comment]
we are aware the newest version has many issues and are working on a fix please use an older version of the mod

**Comment by CyberRat7** [comment]
Fixed in 1.5.3 make sure you are using Temporal Api 1.6.6
