### ISSUE TITLE
[Feature Request] Thermal Expansion sawmill compat

### ISSUE THREAD

**Issue by vizthex123** [CyberRat7/Extra_Compat#11]
Specifically for the wood types from [Ecologics](https://www.curseforge.com/minecraft/mc-mods/ecologics), [Regions Unexplored](https://www.curseforge.com/minecraft/mc-mods/regions-unexplored), [The Outer End](https://www.curseforge.com/minecraft/mc-mods/the-outer-end) and the Ashen Wood from [Quark](https://www.curseforge.com/minecraft/mc-mods/quark) (seems like TE missed that one with its built-in compat)

Also, could you add the link to this tracker to the navbar on the CurseForge page?

**Comment by CyberRat7** [comment]
Please request features in the discord and not on github https://discord.com/invite/KCEC7ZtYfC

**Comment by vizthex123** [comment]
but that's the point of an issue tracker...?

**Comment by CyberRat7** [comment]
That's a feature request not an issue?

**Comment by vizthex123** [comment]
yeah, but issue trackers also host feature request. First time seeing one that doesn't.
