### ISSUE TITLE
extra compat bug when updating to new version it says player data invalid 

### ISSUE THREAD

**Issue by Thunderrock424242** [CyberRat7/Extra_Compat#13]
so i create or load a new world and it says when it gets to 100% loaded it says player data invalid and exits me to the server page if I revert the update it works as normal.

forge version 47.2.0

Minecraft 1.20.1

**Comment by Veynam** [comment]
Same issue here. Doesnt seem to be fixed as of yet

**Comment by useracct1** [comment]
oop, me too!

**Comment by CyberRat7** [comment]
we are aware the newest version has many issues and are working on a fix please use an older version of the mod

**Comment by CyberRat7** [comment]
Fixed in 1.5.3 make sure you are using Temporal Api 1.6.6
