### ISSUE TITLE
The game crashed whilst mouseclicked event handler Error: java.lang.IllegalStateException: Item: farmersdelight:fried_egg does not exist

### ISSUE THREAD

**Issue by TenKotowsky** [CyberRat7/Extra_Compat#14]
When I disable Extra Compat everything works properly

[latest.log](https://github.com/user-attachments/files/15551803/latest.log)
[crash-2024-06-04_15.05.29-client.txt](https://github.com/user-attachments/files/15551806/crash-2024-06-04_15.05.29-client.txt)

**Comment by MemeLord32** [comment]
Having this same problem. Here is my crash report, and log.

[crash-2024-06-20_22.42.51-client.txt](https://github.com/user-attachments/files/15922091/crash-2024-06-20_22.42.51-client.txt)
[debug-1.log](https://github.com/user-attachments/files/15922095/debug-1.log)

**Comment by CyberRat7** [comment]
we are aware the newest version has many issues and are working on a fix please use an older version of the mod

**Comment by CyberRat7** [comment]
Should be fixed in 1.5.3 make sure you are using Temporal Api 1.6.6

**Comment by Mrglanet** [comment]
Unfortunately, it seems to still be happening. Though it seems to be blaming CorgiLib, I think it's actually this mod.

[debug.log](https://github.com/user-attachments/files/16047326/debug.log)
[latest.log](https://github.com/user-attachments/files/16047327/latest.log)
[crash-2024-06-30_20.58.28-client.txt](https://github.com/user-attachments/files/16047329/crash-2024-06-30_20.58.28-client.txt)

**Comment by CyberRat7** [comment]
Just fixed it in 1.5.5 should be approved on curseforge and modrinth shortly
