### ISSUE TITLE
Crash: java.lang.NoClassDefFoundError: nl/sniffiandros/sniffsweapons/item/GreatSwordItem

### ISSUE THREAD

**Issue by DissonantSynth** [CyberRat7/Extra_Compat#15]
Minecraft 1.20.1
Forge 47.3.1

`Caused by 0: java.lang.NoClassDefFoundError: nl/sniffiandros/sniffsweapons/item/GreatSwordItem
`
[crash-2024-06-25_18.45.44-fml.txt](https://github.com/user-attachments/files/15974793/crash-2024-06-25_18.45.44-fml.txt)
[latest.log](https://github.com/user-attachments/files/15974787/latest.log)

**Comment by Pepelespooder** [comment]
Happening also to me

**Comment by aking4125** [comment]
Reporting the same thing here. Using the current latest version of Extra Compat and Temporal API causes the above crash on startup.

**Comment by Thunderrock424242** [comment]
same happend to me too

**Comment by JustKade** [comment]
Same has happened to me as well
![image](https://github.com/CyberRat7/Extra_Compat/assets/77705929/958c2117-3d6b-4559-b632-8c0d51aaaec1)

**Comment by CyberRat7** [comment]
we are aware the newest version has many issues and are working on a fix please use an older version of the mod

**Comment by CyberRat7** [comment]
Fixed in 1.5.3 make sure you are using Temporal Api 1.6.6
