### ISSUE TITLE
[1.20.1] Game crash

### ISSUE THREAD

**Issue by ocram9** [CyberRat7/Extra_Compat#2]
The game crashes with the latest version (1.3.3) installed. I'm using Forge 47.1.3 on Minecraft version 1.20.1.

Crash report: https://gist.github.com/ocram9/4bd491380d519c75ac9a15159c40e724
Latest log: https://gist.github.com/ocram9/fae9a241f562a00d225e9c9f72e938f2

![Screenshot 2023-11-16 171311](https://github.com/CyberRat7/Extra_Compat/assets/49008532/59d68ca9-eb50-4c78-b3d8-ecbfee1d963f)

**Comment by BugmanBugman** [comment]
Getting this as well, only with 1.3.3

**Comment by BugmanBugman** [comment]
It also messes up rendering for some reason

**Comment by CyberRat7** [comment]
This issue has been resolved with 1.3.4 and I will most likely remove 1.3.3 from the curseforge page because of how buggy it is
