### ISSUE TITLE
[1.20.1] Fail to launch

### ISSUE THREAD

**Issue by ffuentesm** [CyberRat7/Extra_Compat#6]
Extra compat: 1.4.3
Temporal API: 1.4.0
![image](https://github.com/CyberRat7/Extra_Compat/assets/44974827/afedba2e-644e-4d1e-939e-fa08bca8f295)
Log:[crash-2024-02-20_18.08.17-fml.txt](https://github.com/CyberRat7/Extra_Compat/files/14352076/crash-2024-02-20_18.08.17-fml.txt)

**Comment by CyberRat7** [comment]
Try updating Temporal API to 1.4.1 it may fix this problem
