### ISSUE TITLE
Twigs being a required dependancy with clayworks

### ISSUE THREAD

**Issue by Hypermun** [CyberRat7/Extra_Compat#7]
With this mod installed in 1.20.1, clayworks will crash the game without twigs due to missing the "cracked brick" from twigs. Shouldn't this be an optional dependancy?

**Comment by CyberRat7** [comment]
Sorry i cannot seem to replicate this at all through testing, please provide the actual crash log and i can try to fix your problem

**Comment by CyberRat7** [comment]
Working on a fix, use an older version for now

**Comment by CyberRat7** [comment]
This is fixed in the newest version 1.4.10
